{
 "title": "Debezium",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "connector_type",
    "label": "Connector Type",
    "query": "debezium_metrics_TotalNumberOfEventsSeen"
   },
   {
    "name": "connector_name",
    "label": "Connector Name",
    "query": "debezium_metrics_TotalNumberOfEventsSeen{plugin=\"$connector_type\"}"
   }
  ]
 },
 "panels": [
  { "title": "Streaming", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Time since last event",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "debezium_metrics_MilliSecondsSinceLastEvent{plugin=\"$connector_type\",name=\"$connector_name\",context=~\"(binlog|streaming)\"}"
    }
   ]
  },
  {
   "title": "Event count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 3, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "debezium_metrics_TotalNumberOfEventsSeen",
     "legendFormat": "Total events received"
    }
   ]
  },
  {
   "title": "Connected",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "debezium_metrics_Connected{plugin=\"$connector_type\",name=\"$connector_name\",context=~\"(binlog|streaming)\"}"
    }
   ]
  },
  { "title": "Snapshot", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Table count",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "debezium_metrics_TotalTableCount{plugin=\"$connector_type\",name=\"$connector_name\",context=\"snapshot\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Remaining tables",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "debezium_metrics_RemainingTableCount{plugin=\"$connector_type\",name=\"$connector_name\",context=\"snapshot\"}",
     "legendFormat": "Remaining"
    }
   ]
  },
  {
   "title": "Running",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "debezium_metrics_SnapshotRunning{plugin=\"$connector_type\",name=\"$connector_name\",context=\"snapshot\"}"
    }
   ]
  },
  {
   "title": "Completed",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "debezium_metrics_SnapshotCompleted{plugin=\"$connector_type\",name=\"$connector_name\",context=\"snapshot\"}"
    }
   ]
  },
  {
   "title": "Aborted",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "debezium_metrics_SnapshotAborted{plugin=\"$connector_type\",name=\"$connector_name\",context=\"snapshot\"}"
    }
   ]
  },
  {
   "title": "Event count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "debezium_metrics_TotalNumberOfEventsSeen{plugin=\"$connector_type\",name=\"$connector_name\",context=\"snapshot\"}",
     "legendFormat": "Total events received"
    },
    {
     "expr": "debezium_metrics_NumberOfEventsSkipped{plugin=\"$connector_type\",name=\"$connector_name\",context=\"snapshot\"}",
     "legendFormat": "Events skipped"
    }
   ]
  },
  {
   "title": "Rows scanned",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "debezium_metrics_RowsScanned{plugin=\"$connector_type\",name=\"$connector_name\"}"
    }
   ]
  },
  {
   "title": "Kafka Connect",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network traffic rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_connect_metrics_incoming_byte_rate",
       "legendFormat": "Incoming({{client}})"
      },
      {
       "expr": "kafka_connect_metrics_outgoing_byte_rate",
       "legendFormat": "Outgoing({{client}})"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heap Memory",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_bytes_used{area='heap'}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_bytes_max{area='heap'}",
       "legendFormat": "Maximum"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "jvm_threads_current", "legendFormat": "Running" },
      { "expr": "jvm_threads_peak", "legendFormat": "Maximum" },
      { "expr": "jvm_threads_started_total", "legendFormat": "Started in total" }
     ]
    }
   ]
  }
 ]
}